steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/llm-repo/llama2-7b', '.' ]
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/llm-repo/llama2-7b'
  # Push the container image to Artifact Registry, get sha256 of the image
  